/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as NewsfeedIndexRouteImport } from './routes/newsfeed/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as ProfileUserRouteImport } from './routes/profile/user'
import { Route as ProfileLinkdingRouteImport } from './routes/profile/linkding'
import { Route as ModelsLeaderboardRouteImport } from './routes/models/leaderboard'
import { Route as ModelsEmbeddingleaderboardRouteImport } from './routes/models/embeddingleaderboard'
import { Route as AppsOwuiRouteImport } from './routes/apps/owui'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const NewsfeedIndexRoute = NewsfeedIndexRouteImport.update({
  id: '/newsfeed/',
  path: '/newsfeed/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any)
const ProfileUserRoute = ProfileUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLinkdingRoute = ProfileLinkdingRouteImport.update({
  id: '/linkding',
  path: '/linkding',
  getParentRoute: () => ProfileRoute,
} as any)
const ModelsLeaderboardRoute = ModelsLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsEmbeddingleaderboardRoute =
  ModelsEmbeddingleaderboardRouteImport.update({
    id: '/embeddingleaderboard',
    path: '/embeddingleaderboard',
    getParentRoute: () => ModelsRoute,
  } as any)
const AppsOwuiRoute = AppsOwuiRouteImport.update({
  id: '/owui',
  path: '/owui',
  getParentRoute: () => AppsRoute,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/examples': typeof ExamplesRoute
  '/images': typeof ImagesRoute
  '/models': typeof ModelsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/models/embeddingleaderboard': typeof ModelsEmbeddingleaderboardRoute
  '/models/leaderboard': typeof ModelsLeaderboardRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps/': typeof AppsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/newsfeed/': typeof NewsfeedIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/examples': typeof ExamplesRoute
  '/images': typeof ImagesRoute
  '/redirect': typeof RedirectRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/models/embeddingleaderboard': typeof ModelsEmbeddingleaderboardRoute
  '/models/leaderboard': typeof ModelsLeaderboardRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps': typeof AppsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/news': typeof NewsIndexRoute
  '/newsfeed': typeof NewsfeedIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/examples': typeof ExamplesRoute
  '/images': typeof ImagesRoute
  '/models': typeof ModelsRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/apps/owui': typeof AppsOwuiRoute
  '/models/embeddingleaderboard': typeof ModelsEmbeddingleaderboardRoute
  '/models/leaderboard': typeof ModelsLeaderboardRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps/': typeof AppsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/newsfeed/': typeof NewsfeedIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/customScript.js'
    | '/deferred'
    | '/examples'
    | '/images'
    | '/models'
    | '/news'
    | '/profile'
    | '/redirect'
    | '/apps/owui'
    | '/models/embeddingleaderboard'
    | '/models/leaderboard'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps/'
    | '/models/'
    | '/news/'
    | '/newsfeed/'
    | '/profile/'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/examples'
    | '/images'
    | '/redirect'
    | '/apps/owui'
    | '/models/embeddingleaderboard'
    | '/models/leaderboard'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps'
    | '/models'
    | '/news'
    | '/newsfeed'
    | '/profile'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/apps'
    | '/customScript.js'
    | '/deferred'
    | '/examples'
    | '/images'
    | '/models'
    | '/news'
    | '/profile'
    | '/redirect'
    | '/_pathlessLayout/_nested-layout'
    | '/apps/owui'
    | '/models/embeddingleaderboard'
    | '/models/leaderboard'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps/'
    | '/models/'
    | '/news/'
    | '/newsfeed/'
    | '/profile/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AppsRoute: typeof AppsRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  ExamplesRoute: typeof ExamplesRoute
  ImagesRoute: typeof ImagesRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  NewsfeedIndexRoute: typeof NewsfeedIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/newsfeed/': {
      id: '/newsfeed/'
      path: '/newsfeed'
      fullPath: '/newsfeed/'
      preLoaderRoute: typeof NewsfeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/profile/user': {
      id: '/profile/user'
      path: '/user'
      fullPath: '/profile/user'
      preLoaderRoute: typeof ProfileUserRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/linkding': {
      id: '/profile/linkding'
      path: '/linkding'
      fullPath: '/profile/linkding'
      preLoaderRoute: typeof ProfileLinkdingRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/models/leaderboard': {
      id: '/models/leaderboard'
      path: '/leaderboard'
      fullPath: '/models/leaderboard'
      preLoaderRoute: typeof ModelsLeaderboardRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/embeddingleaderboard': {
      id: '/models/embeddingleaderboard'
      path: '/embeddingleaderboard'
      fullPath: '/models/embeddingleaderboard'
      preLoaderRoute: typeof ModelsEmbeddingleaderboardRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/apps/owui': {
      id: '/apps/owui'
      path: '/owui'
      fullPath: '/apps/owui'
      preLoaderRoute: typeof AppsOwuiRouteImport
      parentRoute: typeof AppsRoute
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface AppsRouteChildren {
  AppsOwuiRoute: typeof AppsOwuiRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsOwuiRoute: AppsOwuiRoute,
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface ModelsRouteChildren {
  ModelsEmbeddingleaderboardRoute: typeof ModelsEmbeddingleaderboardRoute
  ModelsLeaderboardRoute: typeof ModelsLeaderboardRoute
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsEmbeddingleaderboardRoute: ModelsEmbeddingleaderboardRoute,
  ModelsLeaderboardRoute: ModelsLeaderboardRoute,
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface NewsRouteChildren {
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface ProfileRouteChildren {
  ProfileLinkdingRoute: typeof ProfileLinkdingRoute
  ProfileUserRoute: typeof ProfileUserRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileLinkdingRoute: ProfileLinkdingRoute,
  ProfileUserRoute: ProfileUserRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AppsRoute: AppsRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  ExamplesRoute: ExamplesRoute,
  ImagesRoute: ImagesRoute,
  ModelsRoute: ModelsRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RedirectRoute: RedirectRoute,
  NewsfeedIndexRoute: NewsfeedIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
