/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjscopyRouteImport } from './routes/customScript[.]js copy'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as ProfileUserRouteImport } from './routes/profile/user'
import { Route as ProfileLinkdingRouteImport } from './routes/profile/linkding'
import { Route as ProfileBytestashRouteImport } from './routes/profile/bytestash'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AppsRocketchatRouteImport } from './routes/apps/rocketchat'
import { Route as AppsOwuiRouteImport } from './routes/apps/owui'
import { Route as AppsLangflowRouteImport } from './routes/apps/langflow'
import { Route as AppsForgejoRouteImport } from './routes/apps/forgejo'
import { Route as AppsComfyuiRouteImport } from './routes/apps/comfyui'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjscopyRoute = CustomScriptDotjscopyRouteImport.update({
  id: '/customScript.js copy',
  path: '/customScript.js copy',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const ProfileUserRoute = ProfileUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLinkdingRoute = ProfileLinkdingRouteImport.update({
  id: '/linkding',
  path: '/linkding',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBytestashRoute = ProfileBytestashRouteImport.update({
  id: '/bytestash',
  path: '/bytestash',
  getParentRoute: () => ProfileRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const AppsRocketchatRoute = AppsRocketchatRouteImport.update({
  id: '/rocketchat',
  path: '/rocketchat',
  getParentRoute: () => AppsRoute,
} as any)
const AppsOwuiRoute = AppsOwuiRouteImport.update({
  id: '/owui',
  path: '/owui',
  getParentRoute: () => AppsRoute,
} as any)
const AppsLangflowRoute = AppsLangflowRouteImport.update({
  id: '/langflow',
  path: '/langflow',
  getParentRoute: () => AppsRoute,
} as any)
const AppsForgejoRoute = AppsForgejoRouteImport.update({
  id: '/forgejo',
  path: '/forgejo',
  getParentRoute: () => AppsRoute,
} as any)
const AppsComfyuiRoute = AppsComfyuiRouteImport.update({
  id: '/comfyui',
  path: '/comfyui',
  getParentRoute: () => AppsRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/customScript.js copy': typeof CustomScriptDotjscopyRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/apps/': typeof AppsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/customScript.js copy': typeof CustomScriptDotjscopyRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/apps': typeof AppsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/customScript.js copy': typeof CustomScriptDotjscopyRoute
  '/deferred': typeof DeferredRoute
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/apps/': typeof AppsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/customScript.js'
    | '/customScript.js copy'
    | '/deferred'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/users'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/posts/$postId'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/users/$userId'
    | '/apps/'
    | '/posts/'
    | '/profile/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/customScript.js copy'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/posts/$postId'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/users/$userId'
    | '/apps'
    | '/posts'
    | '/profile'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/apps'
    | '/customScript.js'
    | '/customScript.js copy'
    | '/deferred'
    | '/posts'
    | '/profile'
    | '/redirect'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/posts/$postId'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/users/$userId'
    | '/apps/'
    | '/posts/'
    | '/profile/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
    | '/posts_/$postId/deep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AppsRoute: typeof AppsRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  CustomScriptDotjscopyRoute: typeof CustomScriptDotjscopyRoute
  DeferredRoute: typeof DeferredRoute
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js copy': {
      id: '/customScript.js copy'
      path: '/customScript.js copy'
      fullPath: '/customScript.js copy'
      preLoaderRoute: typeof CustomScriptDotjscopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/profile/user': {
      id: '/profile/user'
      path: '/user'
      fullPath: '/profile/user'
      preLoaderRoute: typeof ProfileUserRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/linkding': {
      id: '/profile/linkding'
      path: '/linkding'
      fullPath: '/profile/linkding'
      preLoaderRoute: typeof ProfileLinkdingRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/bytestash': {
      id: '/profile/bytestash'
      path: '/bytestash'
      fullPath: '/profile/bytestash'
      preLoaderRoute: typeof ProfileBytestashRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/apps/rocketchat': {
      id: '/apps/rocketchat'
      path: '/rocketchat'
      fullPath: '/apps/rocketchat'
      preLoaderRoute: typeof AppsRocketchatRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/owui': {
      id: '/apps/owui'
      path: '/owui'
      fullPath: '/apps/owui'
      preLoaderRoute: typeof AppsOwuiRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/langflow': {
      id: '/apps/langflow'
      path: '/langflow'
      fullPath: '/apps/langflow'
      preLoaderRoute: typeof AppsLangflowRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/forgejo': {
      id: '/apps/forgejo'
      path: '/forgejo'
      fullPath: '/apps/forgejo'
      preLoaderRoute: typeof AppsForgejoRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/comfyui': {
      id: '/apps/comfyui'
      path: '/comfyui'
      fullPath: '/apps/comfyui'
      preLoaderRoute: typeof AppsComfyuiRouteImport
      parentRoute: typeof AppsRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface AppsRouteChildren {
  AppsComfyuiRoute: typeof AppsComfyuiRoute
  AppsForgejoRoute: typeof AppsForgejoRoute
  AppsLangflowRoute: typeof AppsLangflowRoute
  AppsOwuiRoute: typeof AppsOwuiRoute
  AppsRocketchatRoute: typeof AppsRocketchatRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsComfyuiRoute: AppsComfyuiRoute,
  AppsForgejoRoute: AppsForgejoRoute,
  AppsLangflowRoute: AppsLangflowRoute,
  AppsOwuiRoute: AppsOwuiRoute,
  AppsRocketchatRoute: AppsRocketchatRoute,
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProfileRouteChildren {
  ProfileBytestashRoute: typeof ProfileBytestashRoute
  ProfileLinkdingRoute: typeof ProfileLinkdingRoute
  ProfileUserRoute: typeof ProfileUserRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBytestashRoute: ProfileBytestashRoute,
  ProfileLinkdingRoute: ProfileLinkdingRoute,
  ProfileUserRoute: ProfileUserRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AppsRoute: AppsRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  CustomScriptDotjscopyRoute: CustomScriptDotjscopyRoute,
  DeferredRoute: DeferredRoute,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RedirectRoute: RedirectRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
