/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsfeedRouteImport } from './routes/newsfeed'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as NewsfeedIndexRouteImport } from './routes/newsfeed/index'
import { Route as ModelsIndexRouteImport } from './routes/models/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as ProfileUserRouteImport } from './routes/profile/user'
import { Route as ProfileLinkdingRouteImport } from './routes/profile/linkding'
import { Route as ProfileBytestashRouteImport } from './routes/profile/bytestash'
import { Route as AppsRocketchatRouteImport } from './routes/apps/rocketchat'
import { Route as AppsOwuiRouteImport } from './routes/apps/owui'
import { Route as AppsLangflowRouteImport } from './routes/apps/langflow'
import { Route as AppsForgejoRouteImport } from './routes/apps/forgejo'
import { Route as AppsComfyuiRouteImport } from './routes/apps/comfyui'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsfeedRoute = NewsfeedRouteImport.update({
  id: '/newsfeed',
  path: '/newsfeed',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const NewsfeedIndexRoute = NewsfeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsfeedRoute,
} as any)
const ModelsIndexRoute = ModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModelsRoute,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsRoute,
} as any)
const ProfileUserRoute = ProfileUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileLinkdingRoute = ProfileLinkdingRouteImport.update({
  id: '/linkding',
  path: '/linkding',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileBytestashRoute = ProfileBytestashRouteImport.update({
  id: '/bytestash',
  path: '/bytestash',
  getParentRoute: () => ProfileRoute,
} as any)
const AppsRocketchatRoute = AppsRocketchatRouteImport.update({
  id: '/rocketchat',
  path: '/rocketchat',
  getParentRoute: () => AppsRoute,
} as any)
const AppsOwuiRoute = AppsOwuiRouteImport.update({
  id: '/owui',
  path: '/owui',
  getParentRoute: () => AppsRoute,
} as any)
const AppsLangflowRoute = AppsLangflowRouteImport.update({
  id: '/langflow',
  path: '/langflow',
  getParentRoute: () => AppsRoute,
} as any)
const AppsForgejoRoute = AppsForgejoRouteImport.update({
  id: '/forgejo',
  path: '/forgejo',
  getParentRoute: () => AppsRoute,
} as any)
const AppsComfyuiRoute = AppsComfyuiRouteImport.update({
  id: '/comfyui',
  path: '/comfyui',
  getParentRoute: () => AppsRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/models': typeof ModelsRouteWithChildren
  '/newsfeed': typeof NewsfeedRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps/': typeof AppsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/newsfeed/': typeof NewsfeedIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/redirect': typeof RedirectRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps': typeof AppsIndexRoute
  '/models': typeof ModelsIndexRoute
  '/newsfeed': typeof NewsfeedIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/apps': typeof AppsRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/deferred': typeof DeferredRoute
  '/models': typeof ModelsRouteWithChildren
  '/newsfeed': typeof NewsfeedRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/apps/comfyui': typeof AppsComfyuiRoute
  '/apps/forgejo': typeof AppsForgejoRoute
  '/apps/langflow': typeof AppsLangflowRoute
  '/apps/owui': typeof AppsOwuiRoute
  '/apps/rocketchat': typeof AppsRocketchatRoute
  '/profile/bytestash': typeof ProfileBytestashRoute
  '/profile/linkding': typeof ProfileLinkdingRoute
  '/profile/user': typeof ProfileUserRoute
  '/apps/': typeof AppsIndexRoute
  '/models/': typeof ModelsIndexRoute
  '/newsfeed/': typeof NewsfeedIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/customScript.js'
    | '/deferred'
    | '/models'
    | '/newsfeed'
    | '/profile'
    | '/redirect'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps/'
    | '/models/'
    | '/newsfeed/'
    | '/profile/'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/deferred'
    | '/redirect'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps'
    | '/models'
    | '/newsfeed'
    | '/profile'
    | '/route-a'
    | '/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/apps'
    | '/customScript.js'
    | '/deferred'
    | '/models'
    | '/newsfeed'
    | '/profile'
    | '/redirect'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/apps/comfyui'
    | '/apps/forgejo'
    | '/apps/langflow'
    | '/apps/owui'
    | '/apps/rocketchat'
    | '/profile/bytestash'
    | '/profile/linkding'
    | '/profile/user'
    | '/apps/'
    | '/models/'
    | '/newsfeed/'
    | '/profile/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/auth/$'
    | '/api/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  AppsRoute: typeof AppsRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DeferredRoute: typeof DeferredRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  NewsfeedRoute: typeof NewsfeedRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsfeed': {
      id: '/newsfeed'
      path: '/newsfeed'
      fullPath: '/newsfeed'
      preLoaderRoute: typeof NewsfeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/newsfeed/': {
      id: '/newsfeed/'
      path: '/'
      fullPath: '/newsfeed/'
      preLoaderRoute: typeof NewsfeedIndexRouteImport
      parentRoute: typeof NewsfeedRoute
    }
    '/models/': {
      id: '/models/'
      path: '/'
      fullPath: '/models/'
      preLoaderRoute: typeof ModelsIndexRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/apps/': {
      id: '/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof AppsRoute
    }
    '/profile/user': {
      id: '/profile/user'
      path: '/user'
      fullPath: '/profile/user'
      preLoaderRoute: typeof ProfileUserRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/linkding': {
      id: '/profile/linkding'
      path: '/linkding'
      fullPath: '/profile/linkding'
      preLoaderRoute: typeof ProfileLinkdingRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/bytestash': {
      id: '/profile/bytestash'
      path: '/bytestash'
      fullPath: '/profile/bytestash'
      preLoaderRoute: typeof ProfileBytestashRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/apps/rocketchat': {
      id: '/apps/rocketchat'
      path: '/rocketchat'
      fullPath: '/apps/rocketchat'
      preLoaderRoute: typeof AppsRocketchatRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/owui': {
      id: '/apps/owui'
      path: '/owui'
      fullPath: '/apps/owui'
      preLoaderRoute: typeof AppsOwuiRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/langflow': {
      id: '/apps/langflow'
      path: '/langflow'
      fullPath: '/apps/langflow'
      preLoaderRoute: typeof AppsLangflowRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/forgejo': {
      id: '/apps/forgejo'
      path: '/forgejo'
      fullPath: '/apps/forgejo'
      preLoaderRoute: typeof AppsForgejoRouteImport
      parentRoute: typeof AppsRoute
    }
    '/apps/comfyui': {
      id: '/apps/comfyui'
      path: '/comfyui'
      fullPath: '/apps/comfyui'
      preLoaderRoute: typeof AppsComfyuiRouteImport
      parentRoute: typeof AppsRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface AppsRouteChildren {
  AppsComfyuiRoute: typeof AppsComfyuiRoute
  AppsForgejoRoute: typeof AppsForgejoRoute
  AppsLangflowRoute: typeof AppsLangflowRoute
  AppsOwuiRoute: typeof AppsOwuiRoute
  AppsRocketchatRoute: typeof AppsRocketchatRoute
  AppsIndexRoute: typeof AppsIndexRoute
}

const AppsRouteChildren: AppsRouteChildren = {
  AppsComfyuiRoute: AppsComfyuiRoute,
  AppsForgejoRoute: AppsForgejoRoute,
  AppsLangflowRoute: AppsLangflowRoute,
  AppsOwuiRoute: AppsOwuiRoute,
  AppsRocketchatRoute: AppsRocketchatRoute,
  AppsIndexRoute: AppsIndexRoute,
}

const AppsRouteWithChildren = AppsRoute._addFileChildren(AppsRouteChildren)

interface ModelsRouteChildren {
  ModelsIndexRoute: typeof ModelsIndexRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsIndexRoute: ModelsIndexRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

interface NewsfeedRouteChildren {
  NewsfeedIndexRoute: typeof NewsfeedIndexRoute
}

const NewsfeedRouteChildren: NewsfeedRouteChildren = {
  NewsfeedIndexRoute: NewsfeedIndexRoute,
}

const NewsfeedRouteWithChildren = NewsfeedRoute._addFileChildren(
  NewsfeedRouteChildren,
)

interface ProfileRouteChildren {
  ProfileBytestashRoute: typeof ProfileBytestashRoute
  ProfileLinkdingRoute: typeof ProfileLinkdingRoute
  ProfileUserRoute: typeof ProfileUserRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileBytestashRoute: ProfileBytestashRoute,
  ProfileLinkdingRoute: ProfileLinkdingRoute,
  ProfileUserRoute: ProfileUserRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  AppsRoute: AppsRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DeferredRoute: DeferredRoute,
  ModelsRoute: ModelsRouteWithChildren,
  NewsfeedRoute: NewsfeedRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RedirectRoute: RedirectRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
